### ISSUE TITLE
[0.6.0] All social logins are broken, including discord

### ISSUE THREAD

**Issue by fungilation** [nhost/hasura-auth#137]
Example flow on logging in with Discord
- http://localhost:1337/v1/auth/signin/provider/discord?redirectTo=http%3A%2F%2Flocalhost%3A3000%2Fprofile, 302 redirect to
-  http://localhost:3000/profile?error=invalid-request&errorDescription=%22redirectTo%22%20must%20be%20one%20of%20[https://midnightsociety.com/claws-nft,%20https://vsm-nft-fe.vercel.app/claws-nft,%20http://localhost:3000/claws-nft]

hasura-auth needs E2E testing with a FE sample app. with say Playwright

**Comment by plmercereau** [comment]
Hello Gary,

Thanks for this issue. [This PR](https://github.com/nhost/hasura-auth/pull/142) will solve the problem.
In the meantime, you could add `http://localhost:3000/profile` to the `AUTH_ACCESS_CONTROL_ALLOWED_REDIRECT_URLS` environment variable (or `auth.access_control.allowed_redirect_urls` in the `config.yaml` file if using the Nhost CLI), from the url you share, I guess you would need to change from
- from `https://midnightsociety.com/claws-nft,https://vsm-nft-fe.vercel.app/claws-nft,http://localhost:3000/claws-nft`
- to `https://midnightsociety.com/claws-nft,https://vsm-nft-fe.vercel.app/claws-nft,http://localhost:3000/claws-nft,http://localhost:3000/profile`

In next release, any value starting with the `AUTH_CLIENT_URL` will be valid, or any value in `AUTH_ACCESS_CONTROL_ALLOWED_REDIRECT_URLS`. If no value is given, it falls back to `AUTH_CLIENT_URL`

About tests, yes, I couldn't agree more, we need to improve the current coverage (70%) and include Oauth tests. 

We tried to automate e2e Oauth tests in HBP approximately two years ago, but it turned out Google et al. set very strong security measures to block bots / automations to use Oauth in a CI pipeline. We made several attempts, the most promising being based on Pupeteer, but no matter what kind of hacky, obscure way we set it, Google was always able to detect the non-human nature of the connection attempt and was blocking it. That's maybe water under the bridge, so it's time for us to check any change in the status quo - let's continue this discussion on the other issue you opened!

**Comment by fungilation** [comment]
suggestion for future. Can `AUTH_ACCESS_CONTROL_ALLOWED_REDIRECT_URLS` be deprecated entirely? Should rely on `AUTH_CLIENT_URL` only, so apps whitelist only domains, not specific paths the login want to redirect to. This here is 3x3 (3 domains, 3 paths) and keep updating this is tedious. Security like CORS should lie at domain level?

**Comment by elitan** [comment]
I think it's good that we have two separate variables here.

`AUTH_CLIENT_URL` is the default URL of your app. If you don't specify a `redirectUrl` Hasura Auth will fall back to this value. This would not be possible if `AUTH_CLIENT_URL` was an array of values.

**Comment by fungilation** [comment]
Sure, only since `AUTH_CLIENT_URL` is having dual purposes: allowed redirect whitelisting, and default redirectTo. If the whitelisting purpose is separated out as a dedicated var, that var could be an array of allowed domains.

I just don't see the security value in `AUTH_ACCESS_CONTROL_ALLOWED_REDIRECT_URLS` in whitelisting paths. The 0.6.0 breakage is on it being "assumed" required, but I for one isn't because it's tedious to update. My 2c
