### ISSUE TITLE
Do not prevent reading of custom permission variables if one is incorrect

### ISSUE THREAD

**Issue by ArieJones** [nhost/hasura-auth#204]
I was trying to test the capabilities of the current dot notation for custom permission variables and discovered if you enter in one value that cannot be read then it just quietly fails for all of them and none are utilized. 

I would think the preferred method would be to just log the failure somehow and then carry on with trying to read the other values. 

So in my example I tried to add a value to try and access the a metadata column value... but this seems not allowed currently. In doing so none of the 6 other custom permission variables were returned.. 

![image](https://user-images.githubusercontent.com/14859781/175546454-bb3fae73-6cc0-48c5-b56a-d21fd62b244f.png)

**Comment by plmercereau** [comment]
The hasura-auth are now available on the Nhost Cloud, and we will enhance their readability with [this PR](https://github.com/nhost/hasura-auth/pull/256).

The `metadata` column is a JSON column, and JSON columns are currently a limitation of custom claims.
For instance, if your define a claim with the path `user.metadata.a`, it will generate under the hood the following query:
```graphql
user(id: "user-uuid") {
  metadata {
    a
  }
}
```
which is incorrect whereas Hasura does not support browsing into JSON columns (because they are not typed with a schema).
The detection of JSON columns requires a lot more efforts as we would need to build the GraphQL query not only from the JMESPath/JSONata expression, but also from the GraphQL schema.
