### ISSUE TITLE
What is reason behind allowedRoles during sign-up?

### ISSUE THREAD

**Issue by abdullah2993** [nhost/hasura-auth#216]
I'm not sure if I understand the usage of allowedRole input in case of sign-up, wouldn't that mean the end-users/client can add as many roles as they want to the allowed list? for example while singing-up someone can pass allowedRole for something like `superadmin` etc?
Or the goal here is that hasura-auth shouldn't be directly integrated in clients?

**Comment by Morstis** [comment]
Even so I am not sure if my current findings are correct, I want to share what I found out to this issue.

At first, I was thinking the exact same as @abdullah2993. It seems that you can give the new registered user any role if you pass it in the options parameter in the post request to ```auth/signup/email-password```.
So something like this body should give the user the ability to get the admin role:
```{
    "email": "dev@example.com",
    "password": "asdasdasd",
    "options": {
        "allowedRoles": ["me", "user", "admin"]
    }
} 
```

But I am getting the error: ``` "message": "\"options.allowedRoles[2]\" does not match any of the allowed types"```

# Why is this?
At first, I want to say that this functionality is not documented anywhere and is kinda unintuitive.

You can only set the allowedRoles Array on registration to roles that are defined in the AUTH_USER_ALLOWED_ROLES environment variable. Or in the  AUTH_USER_DEFAULT_ALLOWED_ROLES variable. Those can be changes in the web interface under Settings->Roles and Permissions
![image](https://user-images.githubusercontent.com/30554710/192059459-ff1b169e-37bb-45c2-ae68-ab00c7705251.png)

Roles that are set here can be changed on register.

BUT if there are not present in the roles table in hasura (auth->roles) you will get an internal error on registration, because the user can not created, because of a foreign key violation I guess (relation of users->users_roles->roles depending on fk_role)

Anyways if you update said roles table for example like this:
![image](https://user-images.githubusercontent.com/30554710/192060202-5fcb81bc-b576-40ad-8d85-0701ef592852.png)

You can set the admin in the allowedRoles array on registration but you can NOT set admin2 because it is not defined in the AUTH_USER_ALLOWED_ROLES variable. You will get the error from above. 

But you can change the roles in the auth tab on the web interface:
![image](https://user-images.githubusercontent.com/30554710/192060416-3c896c53-560f-4679-b149-87dc0d995717.png)

In the end all the roles that the user has aka are defined in user_roles are included in the x-hasura-allowed-roles array if the user signs in. 

Hope that helps somehow :)

**Comment by abdullah2993** [comment]
thanks for the detailed reply @Morstis yes it looks like that is the case, I ended up digging through the code to find out how it is handled. Not sure why this feature was added at all, looks like it as added to be able to customize the allowed roles but that doesn't make sense at all since this can be controlled by the end user. 
Almost everything passed in via `options` is validated against the `ENV` variables. e.g. [allowedRoles](https://github.com/nhost/hasura-auth/blob/0c2a48ca638430ecb64d057c2087762f20931d92/src/validation/fields.ts#L54) are compared against the env variable.
I would really like to know the use case where we want to pass default and allowed role to sign-up though.

**Comment by Morstis** [comment]
Maybe you got a usecase if you want to set more default roles in a registration that are uncritical (e.g. "me","user"). For example a "public" role. And with that public role you can create different permissions, like you do with the "me" roles. And likewise to "me" you can pass that role into x-hasura-role if it is in your allowed roles and therefore get a different permission validation.

To make that more clear, a little example:
For the auth.users table I have to following permissions:
The role "user" can select (id, display_name) without any checks
The role "me" can select (*) with check id = x-hasura-user-id
The role "public" can select (id, display_name, locale, email) with any other check like default_roles = x-hasura-role

Therefore to create infinite cases for permission validation with different selects you need infinite roles. And you can grant those in the register with the allowedRoles option.
