### ISSUE TITLE
Available to use Hasura experiment Feature for camelCase Support?

### ISSUE THREAD

**Issue by pythonfullstack** [nhost/hasura-auth#289]
Hasura is supporting GraphQL formatted Query since v2.8.0.

Available to use this feature?

**Comment by elitan** [comment]
We're [manually](https://github.com/nhost/hasura-auth/blob/main/src/metadata.ts) setting GraphQL root fields and field names, so we don't need to rely on this feature from Hasura.

**Comment by pythonfullstack** [comment]
if I am using Hasura only for auth, I don't have to take an advantage of camelCase supporting.
But I am using it for our main service, and I don't want to manually write everything.
To solve the problem, I have to create another Database, which is not what I want.

**Comment by elitan** [comment]
You can still use `graphql-default` as the naming convention for your Hasura instance. Hasura Auth will still work.

But Hasura Auth will not rely on any naming convention from Hausra because we're manually setting the GraphQL root fields and field names. That's why I closed the issue.

**Comment by pythonfullstack** [comment]
I tried to do that but it doesn't work at all.
it failed in validating GraphQL schema when running it.

**Comment by elitan** [comment]
What makes you think the error you got in the screenshot above would be solved by setting `graphql-default` as the naming convention for Hasura?

**Comment by pythonfullstack** [comment]
When I run it with `hasura-default` it works for me, but `graphql-default`.

**Comment by pythonfullstack** [comment]
I'd love to have `Hasura-auth` works for Hasura with `graphql-default`

**Comment by elitan** [comment]
What was the action you tried to do to get the error above?

**Comment by pythonfullstack** [comment]
At the very beginning, I run it with `hasura-default` it worked well.
I noticed that hasura is supporting `graphql-default` and I wanted to use it because I am using it across the project.
I just changed the setting on Hasura console and `Hasura auth` didn't work at all.

I just run command `pnpm dev`/`pnpm start`.

**Comment by lechinoix** [comment]
Hello ! I have the exact same problem here, and cannot find a way to work around it, do you have any idea if this would be difficult to fix ? Can we help you with a PR ?

**Comment by elitan** [comment]
It's currently not supported but we hope to have it available soon.

Until we do, you can name GraphQL root fields etc using camel case in the Hasura Console. I know it's manual work and not ideal, but at least it's an option.

We'll keep this issue open until it's fixed.

**Comment by plmercereau** [comment]
@tdelabro thanks for sharing your work on #316.
In my opinion, we should find a way to make sure hasura-auth works regardless of the Hasura camelCase option being enabled or not.
Starting from this assumption, I see two possibilities:
- create two separate sets of GraphQL operations and GraphQL codegen, and then detect if Hasura is using the camelCase option or not, and pick the right operation accordingly. This will create a significant amount of duplicate code, will be quite hard to maintain, error prone, and hard to test
- Run all the queries from hasura-auth to the DB in SQL rather than through Hasura in GraphQL. It would require to convert the 31-ish current GraphQL operations into SQL operations. Hasura's configuration won't then impact the functioning of hasura-auth, as hasura-auth would not use the GraphQL api anymore.

The second option is not conceptually complex, but requires a significant amount of refactoring.
Thoughts, a better solution to suggest?
