### ISSUE TITLE
Improve SMTP logging output

### ISSUE THREAD

**Issue by mirko314** [nhost/hasura-auth#321]
It is currently impossible to debug **why** a custom SMTP connection fails as the only log entry related to this is a error 500 when requesting an email e.g:
```
2023-01-04 16:26:56 hasura-auth {"latencyInNs":32000000,"level":"error","message":"POST /user/password/reset 500 32ms","method":"POST","statusCode":500,"url":"/user/password/reset"}
```
It would be good to get the actual reason why e.g sending the email failed.
Additionally, it would be awesome to be able to send a testing email from the NHOST dashboard when setting the SMTP settings.

**Comment by guicurcio** [comment]
Hello Mirko, thanks for making this issue; I've replied to you in Discord (I've cheked the app states and deployment logs and haven't found anything amiss, plus the SMTP columns are filled):  
\- We have moved this to the infra team in order to check the services logs. In the meantime, could you double-check that the SMTP settings you've entered are correct? Both the host, user, and auth method?

I agree with `to be able to send a testing email from the NHOST dashboard when setting the SMTP settings.` I think it's a great suggestion, we'll definitely add :+1:

**Comment by mirko314** [comment]
Hey @guicurcio, tried the SMTP settings with the nhost-cli and it worked, so it should work in Prod as well!

**Comment by guicurcio** [comment]
[https://discord.com/channels/552499021260914688/1060038268252594186/1061349935213183047](https://discord.com/channels/552499021260914688/1060038268252594186/1061349935213183047)  
  
\> sheena _—_ Yesterday at 3:25 PM

> i had the same problem (and unfortunately still haven't found a combination of settings that lets me set secure = true) and agree that it would be good to add better logging and debugging for the SMTP settings. otherwise it's just trial and error and pretty hard to do on production. one suggestion @mirko is that we found it was easier to test the settings with the local nhost client until we found a combination that worked. much easier to try a bunch of values locally than to keep updating the settings in the nhost dashboard (especially since you have to make a commit every time since there is no way to force a deploy or restart services with new env)

**Comment by mirko** [comment]
> one suggestion @mirko

wrong mirko :)
  -> @mirko314

**Comment by elitan** [comment]
Fixed here: https://github.com/nhost/hasura-auth/pull/322

We'll try to release this on Nhost ASAP.
