### ISSUE TITLE
When upgrading hasura-auth to 0.24.0 from 0.20.2, AUTH_SERVER_URL has no effect resulting in redirect_uri_mismatch for google auth

### ISSUE THREAD

**Issue by ammarfaris** [nhost/hasura-auth#452]
In hasura-auth 0.20.2, when I set  `AUTH_SERVER_URL=https://api.mydomain.com/v1/auth` , the redirect uri generated by hasura-auth for google provider follows AUTH_SERVER_URL => `https://api.mydomain.com/v1/auth/signin/provider/google/callback`...

but in the latest hasura-auth 0.24.0, even when I set  `AUTH_SERVER_URL=https://api.mydomain.com/v1/auth` ,  the redirect uri generated by hasura-auth is `https://api.mydomain.com/signin/provider/google/callback` **without  `/v1/auth`** 

When i revert back to hasura-auth 0.20.2, the google provider works as intended

**Comment by dbarrosop** [comment]
That's probably related to these two changes:

- https://github.com/nhost/hasura-auth/commit/024258cc121f32bfb14f61de5f94d48e416b4a99: feat: set oauth origin dynamically based on host header
- https://github.com/nhost/hasura-auth/commit/5663eecea78774c4479f84122c88f05bbfd6b3cf: feat: allow configuring api prefix

Basically the URL for the oauth callback is now constructed automatically from both the Host header and the API prefix (which also removes the need for path rewrites) so you will probably need to change your load balancer configuration and migrate from path rewrites to AUTH_API_PREFIX in order to upgrade.

**Comment by ammarfaris** [comment]
> That's probably related to these two changes:
> 
> * [024258c](https://github.com/nhost/hasura-auth/commit/024258cc121f32bfb14f61de5f94d48e416b4a99): feat: set oauth origin dynamically based on host header
> * [5663eec](https://github.com/nhost/hasura-auth/commit/5663eecea78774c4479f84122c88f05bbfd6b3cf): feat: allow configuring api prefix
> 
> Basically the URL for the oauth callback is now constructed automatically from both the Host header and the API prefix (which also removes the need for path rewrites) so you will probably need to change your load balancer configuration and migrate from path rewrites to AUTH_API_PREFIX in order to upgrade.

okay appreciate your explanation. it works now with latest 0.24.0, following your guidance 🙏🏻
