### ISSUE TITLE
Incorrect env var name for AUTH_ALLOWED_USER_ROLES

### ISSUE THREAD

**Issue by mmmmillar** [nhost/hasura-auth#81]
https://github.com/nhost/hasura-auth/blob/a5959413322415a23012d67773ca65387235503d/src/utils/env.ts#L133

I think this should be `AUTH_USER_ALLOWED_ROLES`

**Comment by plmercereau** [comment]
Hello, actually after thoroughly checking the code, it turns out `ALLOWED_USER_ROLES` is never used, but `AUTH_USER_DEFAULT_ALLOWED_ROLES` is (except for tests that I will correct). I will clean the code up so it won't confuse anybody anymore.
Thanks for reviewing the code, it is very helpful to improve its quality!

**Comment by elitan** [comment]
If I remember correctly the purpose of `AUTH_ALLOWED_USER_ROLES` is the specify the allowed user roles that a user can set on registration.

If no roles are set, the user will be given the `AUTH_USER_DEFAULT_ALLOWED_ROLES`.

**Comment by plmercereau** [comment]
Maybe. But right now such mechanism is not implemented nor on top of our roadmap, so I cleaned up the code to stop mentioning this unused variable

**Comment by mmmmillar** [comment]
`AUTH_ALLOWED_USER_ROLES` is used in roles.ts but it was getting its value from `ALLOWED_USER_ROLES` (so it was being used). I think using `AUTH_USER_DEFAULT_ALLOWED_ROLES` is incorrect in this context?
